In [1]:
import torch
from torch import nn

In [3]:
# 在所有侧边填充1个像素
def comp_conv2d(conv2d, X):
    X = X.reshape((1, 1) + X.shape)
    Y = conv2d(X)
    return Y.reshape(Y.shape[2:])
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1)
X = torch.rand(size=(8, 8))
comp_conv2d(conv2d, X).shape

torch.Size([8, 8])

In [5]:
# 填充不同的高度和宽度
conv2d = nn.Conv2d(1, 1, kernel_size=(5, 3), padding=(2, 1))
comp_conv2d(conv2d, X).shape

torch.Size([8, 8])

In [6]:
# 设置高度和宽度的步幅
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)
comp_conv2d(conv2d, X).shape

torch.Size([4, 4])

In [7]:
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
comp_conv2d(conv2d, X).shape

torch.Size([2, 2])

In [9]:
pip install d2l

  Using cached d2l-0.17.6-py3-none-any.whl (112 kB)
  Using cached numpy-1.21.5-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)


  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
Note: you may need to restart the kernel to use updated packages.


In [16]:
# 多输入多输出通道
from d2l import torch as d2l
def corr2d_multi_in(X, K):
    return sum(d2l.corr2d(x, k) for x, k in zip(X, K))

In [17]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
                [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [26]:
# 计算多通道输出的互相关函数
def corr2d_multi_in_out(X, K):
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)
K = torch.stack((K, K + 1, K + 2), 0)
K.shape
K

tensor([[[[[ 0.7074]],

          [[-1.2378]],

          [[ 0.4592]]],


         [[[ 0.7044]],

          [[-0.4327]],

          [[-0.3727]]]],



        [[[[ 1.7074]],

          [[-0.2378]],

          [[ 1.4592]]],


         [[[ 1.7044]],

          [[ 0.5673]],

          [[ 0.6273]]]],



        [[[[ 2.7074]],

          [[ 0.7622]],

          [[ 2.4592]]],


         [[[ 2.7044]],

          [[ 1.5673]],

          [[ 1.6273]]]]])

In [27]:
# 1*1卷积
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape((c_o, c_i))
    Y = torch.matmul(K, X)
    return Y.reshape((c_o, h, w))

X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))
Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)
assert float(torch.abs(Y1 - Y2).sum()) < 1e-6

In [28]:
corr2d_multi_in_out(X, K)

tensor([[[-0.3188, -0.4677, -0.8213],
         [-0.1590,  2.2069,  2.4608],
         [ 0.2992,  2.7912,  1.8766]],

        [[ 0.1226, -2.6426,  5.5231],
         [ 2.3543,  1.6048, -4.9140],
         [-2.0222, -6.1339, -0.8382]]])