In [1]:
# 最大池化 -- 返回滑动窗口中的最大值 输出通道=输入通道
# 平均池化 -- 返回平均值

In [2]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
def pool2d(X, pool_size, mode='max'):       # X为输入 pool_size为池大小 mode为选择最大池还是平均池
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w +1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()
    return Y

In [4]:
# 验证输出 最大
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [5]:
# 平均
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [6]:
# 填充和步幅
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [8]:
# pytorch中步幅和池化窗口大小相同
pool2d = nn.MaxPool2d(3) # 3*3的窗口
pool2d(X)

tensor([[[[10.]]]])

In [9]:
# 手动调整填充和步幅
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [11]:
# 设定任意大小的矩形池化窗口并设定填充和步幅
pool2d = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [12]:
# 在不同通道上的运算
X = torch.cat((X, X + 1), 1) # X为第一通道 X+1为第二通道
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [13]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])